2025-09-13 08:34:44.194249 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 56, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ~~~~^^^^
IndexError: list index out of range

2025-09-13 08:34:44.889492 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 56, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ~~~~^^^^
IndexError: list index out of range

2025-09-13 08:34:45.862768 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 56, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ~~~~^^^^
IndexError: list index out of range

2025-09-13 08:34:46.875490 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 56, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ~~~~^^^^
IndexError: list index out of range

2025-09-13 08:34:47.880955 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 56, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ~~~~^^^^
IndexError: list index out of range

2025-09-13 08:34:48.877061 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:49.876705 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:50.899794 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:51.877448 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:52.879677 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:53.995058 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:54.874490 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:55.904605 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:56.886625 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:57.883847 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:59.472048 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:34:59.902856 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:35:00.904501 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_ask_price =    asks[0][0]
                        ~~~~^^^
IndexError: list index out of range

2025-09-13 08:36:12.759114 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:12.832630 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:12.880692 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:12.963107 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:13.017773 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:13.097821 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:13.150567 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

2025-09-13 08:36:13.217181 - Traceback (most recent call last):
  File "C:\Users\user\Desktop\trade\dashboard\views_pages\depth_handler.py", line 58, in handle_a_depth_pulse
    best_bid_price =    bids[-1][0]
                        ^^^^^^^
IndexError: list index out of range

